-- MySQL Script generated by MySQL Workbench
-- Thu May 26 15:50:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_tickets_for_snacks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tickets_for_snacks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tickets_for_snacks` DEFAULT CHARACTER SET utf8 ;
USE `db_tickets_for_snacks` ;

-- -----------------------------------------------------
-- Table `db_tickets_for_snacks`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tickets_for_snacks`.`tb_usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NOT NULL COMMENT 'link da foto (default image)',
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tickets_for_snacks`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tickets_for_snacks`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_tema_categoria` VARCHAR(255) NOT NULL,
  `descricao_categoria` VARCHAR(1000) NULL,
  `icone_categoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tickets_for_snacks`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tickets_for_snacks`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_ticket` VARCHAR(50) NOT NULL,
  `valor_ticket` DECIMAL(6,2) NOT NULL,
  `descricao_ticket` VARCHAR(1000) NULL,
  `data_horario_ticket` DATETIME NOT NULL,
  `tb_usuarios_id` BIGINT NOT NULL,
  `tb_categorias_id` BIGINT NOT NULL,
  `foto_ticket` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tb_usuarios_idx` (`tb_usuarios_id` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tb_categorias1_idx` (`tb_categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_usuarios`
    FOREIGN KEY (`tb_usuarios_id`)
    REFERENCES `db_tickets_for_snacks`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tb_categorias1`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `db_tickets_for_snacks`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
